baseURL: "https://wonderfall.dev/"
languageCode: en-us
title: "Wonder's Lab"
theme: WonderMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

permalinks:
  posts: "/:filename"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Wonder's Lab"
  description: "Thoughts and research on security, privacy and pharmacology."
  keywords: [Blog, Research, Security, Privacy]
  author: Wonderfall
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: false
    disableFingerprinting: true

  homeInfoParams:
    Title: "Hi there. I'm a bug on the Internet."
    Content: Thoughts and research on security, privacy, and pharmacology.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/w0nderfall"
    - name: mastodon
      url: "https://mastoid.dev"
    - name: matrix
      url: "https://matrix.to/#/@wonderfall:lysergide.dev"
    - name: github
      url: "https://github.com/Wonderfall"
    - name: rss
      url: /index.xml

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Wonderfall/wonderfall.github.io/blob/main/content"
    Text: "Source code" # edit text
    appendFilePath: true # to append file path to Edit link

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 20
    - identifier: french
      name: french
      url: https://wonderfall.space
      weight: 99
