baseURL: "https://wonderfall.dev/"
languageCode: en-us
title: "Wonder's Lab"
theme: WonderMod
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableGitInfo: true

permalinks:
  posts: "/:filename"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Wonder's Lab"
  description: "Thoughts and research on security, privacy and pharmacology."
  keywords: [Blog, Research, Security, Privacy]
  author: Wonderfall
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: false

  homeInfoParams:
    Title: "Hi there. I'm a bug on the Internet."
    Content: Thoughts and research on security, privacy, and pharmacology.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/w0nderfall"
    - name: mastodon
      url: "https://mastoid.dev"
    - name: matrix
      url: "https://matrix.to/#/@wonderfall:lysergide.dev"
    - name: github
      url: "https://github.com/Wonderfall"
    - name: rss
      url: /index.xml

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Wonderfall/wonderfall.github.io/blob/main/content"
    Text: "Source code" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

#Enabling Search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
    highlight:
        style: dracula
        lineNos: false
        noClasses: false
        guessSyntax: true

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 20
    - identifier: Search
      name: search
      url: /search/
      weight: 30
    - identifier: french
      name: french
      url: https://wonderfall.space
      weight: 99
